# Generated by Django 4.2.4 on 2023-09-03 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='images/')),
                ('description', models.JSONField(default={}, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
