# Generated by Django 4.2.4 on 2023-09-03 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product_delete_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('FAN', 'FAN'), ('LED', 'LED'), ('FAN REGULATOR', 'FAN REGULATOR'), ('SWITCH', 'SWITCH'), ('OTHER', 'OTHER')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.JSONField(default={'power': '220V'}, null=True),
        ),
    ]
