# Generated by Django 4.2.4 on 2023-09-03 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_categories_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'ordering': ['category']},
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.JSONField(default={'param1': 'value1', 'param2': 'value2', 'param3': 'value3', 'param4': 'value4', 'param5': 'value5', 'param6': 'value6', 'param7': 'value7', 'param8': 'value8'}, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
